### ISSUE TITLE
Old fork

### ISSUE THREAD

**Issue by Kerilk** [dorkrawk/darwinning#16]
Hello Dave,

last year I needed a simple/elegant genetic algorithm library in ruby for one of my student internship. I found yours to be the most adapted to what he needed to do. I still needed to change quite a bit of things in order to get it where I wanted. When I stopped I was not sure a pull request was really feasible anymore or my branch mature enough.  More than 30% of the code has been rewritten.

I see that you have received contributions recently, which means that the two branches will diverge from now on. So I though maybe maybe you could be interested in the changes I did before they are irremediably unmergeable.

the fork can be found here:
[https://github.com/Nanosim-LIG/darwinning](https://github.com/Nanosim-LIG/darwinning)

Don't hesitate if you have questions.

Best regards,

Brice

**Comment by dorkrawk** [comment]
Hey Brice,

I'm glad my library was useful for you. I'll take a look at your branch and see if there's anything that makes sense to pull in.

Thanks!

**Comment by dorkrawk** [comment]
Hey Brice,

I just got around to really digging through your the commits in your branch and there's some good stuff there. I've been just picking through a lot of the refactors and just implementing stuff myself but I'd like to give you credit for the work you did. How would you like me to do that?

**Comment by Kerilk** [comment]
Hello Dave,

I am sure a one liner at the end of the read me is enough. Don't hesitate to tell me if you don't feel it is appropriate. Thanks for taking the time to read the code.

**Comment by dorkrawk** [comment]
https://github.com/dorkrawk/darwinning/commit/b6795c92698a5c15acb8fc7b6ccc6be3af06c836
