### ISSUE TITLE
Bug in best_each_generation

### ISSUE THREAD

**Issue by calin-ciobanu** [dorkrawk/darwinning#18]
There is a bug in calculating the `best_each_generation`. The history for each gen is actually not sorted because the fitness is not yet calculated so the `sort_members` calls in initialize and in `make_next_generation` don't have the desired effect.

fix is to remove the sort and adding to history from `initialize` and for `make_next_generation` change to:
```
  def make_next_generation!
    verify_population_size_is_positive!
    sort_members   ####################### sort and add to history before generating new members
    @history << @members
    
    new_members = []

    until new_members.length >= members.length
      m1 = weighted_select
      m2 = weighted_select

      new_members += apply_pairwise_evolutions(m1, m2)
    end

    # In the case of an odd population size, we likely added one too many members.
    new_members.pop if new_members.length > members.length

    @members = apply_non_pairwise_evolutions(new_members)
    @generation += 1
  end
```

**Comment by dorkrawk** [comment]
Thanks for the catch. I just pushed a fix here: https://github.com/dorkrawk/darwinning/commit/3ddf8a1489c20ad6dea6302af555fe5ade3b94ec
