### ISSUE TITLE
undefined method `nice_print'

### ISSUE THREAD

**Issue by script-old** [dorkrawk/darwinning#8]
Hi!
I'm just trying to run examples and see this error.

**Comment by dorkrawk** [comment]
Ahh, I think I pulled that method in one of that last updates. I'll update the examples very soon.  Thanks.

**Comment by dorkrawk** [comment]
Fixed with: https://github.com/dorkrawk/darwinning/commit/931efdeb12847a08a09f4d79ad1ec8ab634a32dc
