### ISSUE TITLE
Just a question on design

### ISSUE THREAD

**Issue by jjgh** [dorkrawk/darwinning#9]
1) I am new to genetic algorithms 2) I haven't examined all the code carefully 3) I don't want to sound nitpicky - I am just learning :) but, is there a specific reason in your design for not storing #fitness inside the object rather than computing it each time it is accessed?

**Comment by dorkrawk** [comment]
Hey! Thanks for checking out the library.  You're totally right that many of these examples are probably wasting time recalculating fitness each time its used. Because I'd like `Organism#fitness` to be as flexible as possible I think the best solution would be to memoize the `#fitness` value.  Something like:

```
def fitness
  @fitness ||= attr_a + attr_b + att_c
end
```

I'll update some of the examples with this pattern.

**Comment by dorkrawk** [comment]
Here's an updated example: https://github.com/dorkrawk/darwinning/commit/cdd96c0cc18d2c537da2ee067272c3e12e2ddfbd

**Comment by jjgh** [comment]
Thanks a lot for clarifying. I've experimented with darwinning to build a system which creates small musical (MIDI) themes, that evolve after being played and rated by the user, so much similar to your cookie example (but I had checked it out only later :) ). So I had temporarily put the rating code inside the #fitness method, and saw how for the same member/object I was asked to listen it and rate it many times (presumably as many times as the number of comparisons with other members it is going through?).
So yeah, I had fixed it by only calculating it first time and then just letting fitness return it for subsequent times, as you did above.. well maybe it could be fun if I could add it to this repo examples.. :) It's using https://github.com/arirusso/unimidi multi platform midi lib. 

I'm seeing though,  that it gets fastly stuck on the same tune. I've googled around a bit and read  that in some conditions genetic algorithms tends to quickly get stuck to local optimum... but again I don't know much about this yet.. (thanks for having given me the opportunity to learn something on this fascinating subject with your gem!).

**Comment by dorkrawk** [comment]
That's a really cool project!  One of my first genetic algorithm projects back in grad school worked with MIDI as well (but it was written in Python). Here's a small paper I published on it: http://socrs.cdm.depaul.edu/2011/program/papers/paper_13.pdf
